---
networks:
  frontend:
    external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:13
    container_name: teleport
    ports:
      - "3080:3080"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    labels: {}
      # -- (Optional) Traefik example configuration
      # traefik.enable: "true"
      # traefik.http.services.teleport.loadbalancer.server.port: "3080"
      # traefik.http.services.teleport.loadbalancer.server.scheme: "https"
      # traefik.http.routers.teleport-http.entrypoints: "web"
      # traefik.http.routers.teleport-http.rule: "Host(`your-server-url`)"
      # traefik.http.routers.teleport-https.entrypoints: "websecure"
      # traefik.http.routers.teleport-https.rule: "Host(`your-server-url`)"
      # traefik.http.routers.teleport-https.tls: "true"
      # traefik.http.routers.teleport-https.tls.certresolver: "your-certresolver"
    networks:
      - frontend
    restart: unless-stopped